"""add company media core"""
from alembic import op
import sqlalchemy as sa

revision = "20260721_0013"
down_revision = "20260720_0012"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("company_media_albums", sa.Column("id", sa.BigInteger, primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("description", sa.Text), sa.Column("cover_media_id", sa.BigInteger), sa.Column("is_restricted", sa.Boolean, nullable=False, server_default=sa.text("false")), sa.Column("created_by_id", sa.BigInteger, sa.ForeignKey("users.id"), nullable=False), sa.Column("updated_by_id", sa.BigInteger, sa.ForeignKey("users.id")), sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.text("true")), sa.Column("deleted_at", sa.DateTime), sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.create_index("idx_company_media_albums_lifecycle", "company_media_albums", ["deleted_at", "is_active"])
    op.execute("CREATE UNIQUE INDEX uq_company_media_albums_active_name ON company_media_albums (lower(name)) WHERE deleted_at IS NULL AND is_active")
    op.create_table("company_media_files", sa.Column("id", sa.BigInteger, primary_key=True), sa.Column("album_id", sa.BigInteger, sa.ForeignKey("company_media_albums.id", ondelete="RESTRICT"), nullable=False), sa.Column("storage_object_id", sa.BigInteger, sa.ForeignKey("storage_objects.id"), nullable=False), sa.Column("display_name", sa.String(255), nullable=False), sa.Column("caption", sa.Text), sa.Column("media_type", sa.String(10), nullable=False), sa.Column("sort_order", sa.Integer), sa.Column("created_by_id", sa.BigInteger, sa.ForeignKey("users.id"), nullable=False), sa.Column("updated_by_id", sa.BigInteger, sa.ForeignKey("users.id")), sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.text("true")), sa.Column("deleted_at", sa.DateTime), sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.UniqueConstraint("storage_object_id", name="uq_company_media_files_storage_object"), sa.CheckConstraint("media_type IN ('image', 'video')", name="ck_company_media_files_media_type"))
    op.create_index("idx_company_media_files_album", "company_media_files", ["album_id", "deleted_at", "is_active"])
    op.create_table("company_media_album_permissions", sa.Column("id", sa.BigInteger, primary_key=True), sa.Column("album_id", sa.BigInteger, sa.ForeignKey("company_media_albums.id", ondelete="CASCADE"), nullable=False), sa.Column("principal_type", sa.String(10), nullable=False), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE")), sa.Column("role_id", sa.BigInteger, sa.ForeignKey("roles.id", ondelete="CASCADE")), *[sa.Column(name, sa.Boolean, nullable=False, server_default=sa.text("false")) for name in ("can_view","can_upload","can_edit","can_delete","can_download","can_share")], sa.Column("created_by_id", sa.BigInteger, sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.CheckConstraint("principal_type IN ('user', 'role')", name="ck_company_media_album_permissions_principal"), sa.CheckConstraint("(user_id IS NOT NULL AND role_id IS NULL) OR (user_id IS NULL AND role_id IS NOT NULL)", name="ck_company_media_album_permissions_principal_xor"), sa.UniqueConstraint("album_id", "user_id", name="uq_company_media_album_permissions_user"), sa.UniqueConstraint("album_id", "role_id", name="uq_company_media_album_permissions_role"))

def downgrade():
    op.drop_table("company_media_album_permissions"); op.drop_table("company_media_files"); op.execute("DROP INDEX IF EXISTS uq_company_media_albums_active_name"); op.drop_table("company_media_albums")
